### ISSUE TITLE
Status message not displayed

### ISSUE THREAD

**Issue by pun-ky** [Cognifide/aem-stubs#15]
When using snippet from WireMock website containing both statusCode and statusMessage configured, when requesting stub status message is not rendered.

**Comment by marcinkp** [comment]
It's not a bug. Seems to be working.
<img width="184" alt="screenshot" src="https://user-images.githubusercontent.com/4946283/82193860-467a0500-98f6-11ea-94a0-fe157e9e7ff4.png">
