### ISSUE TITLE
Support WireMock-native template engine

### ISSUE THREAD

**Issue by pun-ky** [Cognifide/aem-stubs#31]
Due to the hardiness / OSGi incompatibility of Handlebars tpl engine, as a workaround, AEM Stubs are using alternative tpl engine Pebble. Generally speaking, Pebble is more flexible and has more features, however using it causes a mismatch between snippets from WireMock that could be copy/pasted and used on AEM via AEM Stubs and in the end, errors.

Maybe some trick could be used to make Handlebars java OSGi ready and used instead of Pebble to make our WireMock running on AEM more compatible with standalone one.

**Comment by marcinkp** [comment]
Implemented
