### ISSUE TITLE
Support listing registered stubs

### ISSUE THREAD

**Issue by pun-ky** [Cognifide/aem-stubs#33]
consider

- generating somehow application.wadl like in Jersey
- supporting WireMock admin API - http://wiremock.org/docs/api/

**Comment by marcinkp** [comment]
under /stubs/__admin/mappings all mappings defined are returned

NOTE
If dynamic templating is used like
```

    // template file - file name passed as http header
    stubFor(get(urlPathEqualTo("/templated-dynamic"))
            .willReturn(aResponse()
                    .withBody("{{parameters.date}}")
                    .withTransformerParameter("date", {new Date()})))

```

then functionality is not available
