### ISSUE TITLE
Fix Wiremock admin docs endpoint

### ISSUE THREAD

**Issue by pun-ky** [Cognifide/aem-stubs#43]
![](https://user-images.githubusercontent.com/10673561/98407763-808bbe80-2070-11eb-9192-b14f4a9d3237.png)

as of according to wiremock docs, it is a first link mentioned... so it could be quite surprising that it is not working in aem-stubs 

![](https://user-images.githubusercontent.com/10673561/98407868-a9ac4f00-2070-11eb-99ef-9fd19492b52b.png)

**Comment by marcinkp** [comment]
Fixed
